# Default Kibana configuration from kibana-docker.
# from https://github.com/elastic/kibana- 
# docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://192.168.0.42:9200" ]

elasticsearch.ssl.verificationMode: none

elasticsearch.username: "elastic"
elasticsearch.password: "mErAPhone83" 
