# Default Kibana configuration from kibana-docker.
# from https://github.com/elastic/kibana- 
# docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://localhost:9200
elasticsearch.username: "elastic"
elasticsearch.password: "#M3r@jootahaijapanI$" 
